-include .env
export

test:
	pytest

install:
	pip install -r requirements.txt

run:
	python main.py
run2:
	python imperative.py
run3:
	python declarative.py
run4:
	python chat.py
run5:
	python generic_chat.py